version: "3.6"
services:
  

  hasura: # Define the hasura service
    image: hasura/graphql-engine:v2.38.0
    ports:
      - "8083:8080"
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_METADATA_DEFAULTS: '{"backend_configs":{"dataconnector":{"athena":{"uri":"http://data-connector-agent:8081/api/v1/athena"},"mariadb":{"uri":"http://data-connector-agent:8081/api/v1/mariadb"},"mysql8":{"uri":"http://data-connector-agent:8081/api/v1/mysql"},"oracle":{"uri":"http://data-connector-agent:8081/api/v1/oracle"},"snowflake":{"uri":"http://data-connector-agent:8081/api/v1/snowflake"}}}}'
      EXPRESS_SERVER_URL: http://host.docker.internal:4000


  postgres:
    image: postgres:15
    extra_hosts:
    - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

volumes:
  db_data:

# in hasura when i create relationships forexample between users and tasks table are on tasks table i create a forein key that refrs to users id.object relation ship is  arelastionship has one-to one and array relationship is a relationship that has one to many.
#docker desktop.